<?php

namespace Tests\Feature\Author;

use App\Book;
use App\BookFile;
use App\User;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

class AuthorAllBooksLinksTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Storage::fake('old');
    }

    public function testAllBooksLinks()
    {
        $user = User::factory()->create();

        $book = Book::factory()->with_writer()->create();

        $file = BookFile::factory()->txt()->storage_old()->create(['book_id' => $book->id]);

        $url = route('books.files.show', ['book' => $file->book, 'fileName' => $file->name]);

        $author = $book->authors()->first();

        $this->assertNotNull($author);

        $response = $this->actingAs($user)
            ->get(route('authors.books.files.urls', ['author' => $author]))
            ->assertOk()
            ->assertSeeText($url)
            ->assertHeader('Content-Type', 'text/plain; charset=UTF-8');

        $this->assertRegExp('/attachment\;\ filename\=\"'.__('author.links_to_books').'([[:print:]]+)([0-9]+)\.txt\"/iu',
            $response->headers->get('content-disposition'));
    }

    public function testAllBooksLinksDontAddIfBookClosedForDownload()
    {
        $user = User::factory()->create();

        $book = Book::factory()->with_writer()->create();

        $file = BookFile::factory()->txt()->storage_old()->create(['book_id' => $book->id]);

        $url = route('books.files.show', ['book' => $file->book, 'fileName' => $file->name]);

        $author = $book->authors()->first();

        $this->assertNotNull($author);

        $response = $this->actingAs($user)
            ->get(route('authors.books.files.urls', ['author' => $author]))
            ->assertOk()
            ->assertSeeText($url);

        $book->downloadAccessDisable();
        $book->save();

        $response = $this->actingAs($user)
            ->get(route('authors.books.files.urls', ['author' => $author]))
            ->assertOk()
            ->assertDontSeeText($url);
    }

}
